### PR TITLE
Update for Joi 17

### PR DESCRIPTION
**Pull request by chris48s**
- package name has changed (back) to 'joi' (see https://github.com/sideway/joi/issues/2411 )
- joi >=17 is node 12+ only (see https://github.com/sideway/joi/issues/2262 )
- 17.2 distributes TS types in the package (see https://joi.dev/resources/changelog/ )
- Error messages now include quotes for us

This will need to be a major version bump.

### CODE REVIEW

**Comment by chris48s** [comment]
Hmm. Travis doesn't seem to have updated the commit with a build status, but here's the build
https://travis-ci.org/github/dszakallas/joi-extension-semver/builds/731069803

**Comment by paulmelnikow** [comment]
> Error messages now include quotes for us

No longer include quotes, right?

**Comment by dszakallas** [comment]
Or `{{#label}}` already includes the quotes?

**Comment by paulmelnikow** [comment]
Ahhh that makes sense. Probably it would be good to include a test that checks the error message.

**Review by paulmelnikow — COMMENTED** [review]
Thanks for picking this up! Could you update the references to `@hapi/joi` in the readme?

**Comment by chris48s** [comment]
:+1: docs updated. I think we already have enough tests for the error messages e.g:
https://github.com/dszakallas/joi-extension-semver/blob/91363640a5d428bb8f870f38e5bd73ffcb2896ae/index.spec.js#L51
https://github.com/dszakallas/joi-extension-semver/blob/91363640a5d428bb8f870f38e5bd73ffcb2896ae/index.spec.js#L109
etc
That's how I noticed `{{#label}}` now includes the quotes for us :)

**Comment by paulmelnikow** [comment]
Could you resolve the conflict in the lockfile?

**Review by paulmelnikow — APPROVED** [review]

**Comment by chris48s** [comment]
rebased

**Comment by paulmelnikow** [comment]
@chris48s Would you like me to prep the changelog + release, or would you like to do it?

**Pull request merged**
